Repository litentry/litentry-parachain, pull requests merged in 2021-11, with the labels that each got.

#195 feat: quick implementation of transaction fee
  Cargo.lock
  docker/package.json
  docker/yarn.lock
  node/src/command.rs
  node/src/service.rs
  primitives/src/lib.rs
  runtime/Cargo.toml
  runtime/src/constants.rs
  runtime/src/impls/mock.rs
  runtime/src/impls/mod.rs
  runtime/src/impls/tests.rs
  runtime/src/lib.rs
  ts-tests/package.json
  ts-tests/tests/transaction-fee.test.ts
  ts-tests/tests/transfer.test.ts
  ts-tests/tests/utils.ts
  ts-tests/yarn.lock
Labels: S1-pleasereview

#202 Transaction Payment Parameters Update
  runtime/src/constants.rs
  runtime/src/lib.rs
Labels: S1-pleasereview

#200 Add GPLv3 LICENSE
  LICENSE
  README.md
  build.rs
  node/build.rs
  node/src/chain_spec.rs
  node/src/cli.rs
  node/src/command.rs
  node/src/main.rs
  node/src/rpc.rs
  node/src/service.rs
  primitives/src/lib.rs
  runtime/build.rs
  runtime/src/constants.rs
  runtime/src/lib.rs
Labels: S1-pleasereview

#205 Cleanup runtime
  runtime/src/lib.rs
Labels: F4-refactor/optimization, S1-pleasereview

#186 pallet benchmark testing
  Cargo.lock
  Makefile
  node/src/chain_spec.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
  runtime/src/weights/frame_system.rs
  runtime/src/weights/mod.rs
  runtime/src/weights/pallet_balances.rs
  runtime/src/weights/pallet_collator_selection.rs
  runtime/src/weights/pallet_collective.rs
  runtime/src/weights/pallet_democracy.rs
  runtime/src/weights/pallet_identity.rs
  runtime/src/weights/pallet_membership.rs
  runtime/src/weights/pallet_multisig.rs
  runtime/src/weights/pallet_proxy.rs
  runtime/src/weights/pallet_scheduler.rs
  runtime/src/weights/pallet_timestamp.rs
  runtime/src/weights/pallet_treasury.rs
  runtime/src/weights/pallet_utility.rs
  scripts/run-benchmark-pallet.sh
  source/frame_system-weights.rs
  source/local.json
  source/pallet_balances-weights.rs
  source/pallet_utility-weights.rs
Labels: S1-pleasereview

#208 Versioning of runtime wasm and toml in first release
  node/Cargo.toml
  primitives/Cargo.toml
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: S1-pleasereview

#209 Runtime subtle updates
  Cargo.lock
  node/Cargo.toml
  runtime/src/impls/mock.rs
  runtime/src/impls/mod.rs
  runtime/src/impls/tests.rs
Labels: S1-pleasereview

#210 include genesis state and wasm in first release
  .github/workflows/create_release_draft.yml
  scripts/generate-release-notes.sh
Labels: S1-pleasereview

#198 Initial base filter
  runtime/src/lib.rs
  ts-tests/package.json
  ts-tests/tests/base-filter.test.ts
Labels: S1-pleasereview

#211 genesis config finalization
  .gitignore
  docker/package.json
  docker/yarn.lock
  node/res/genesis_info/prod.json
  scripts/generate-prod-chain-spec.sh
Labels: S1-pleasereview

#213 Backport from Release v0.9.0
  .github/workflows/build_docker_with_args.yml
  docker/parachain-launch-config-dev.yml
  docker/parachain-launch-config-staging.yml
  node/res/chain_spec/prod-plain.json
  node/res/chain_spec/prod.json
  node/res/genesis_info/prod.json
  node/src/cli.rs
  node/src/command.rs
  runtime/src/lib.rs
  scripts/launch-local-binary.sh
  ts-tests/config.ci.json
  ts-tests/tests/register-parachain.ts
Labels: S1-pleasereview

#223 register parachain for launch-local-binary
  Makefile
  scripts/launch-local-binary.sh
  scripts/run-ci-test.sh
Labels: S1-pleasereview

#222 Misc improvements to GA and scripts
  .github/workflows/build_wasm.yml
  Cargo.lock
  docker/parachain-launch-config-dev.yml
  scripts/bump-code-versions.sh
Labels: S1-pleasereview

#230 add try-runtime support
  .github/workflows/build_docker_with_args.yml
  node/Cargo.toml
  node/src/cli.rs
  node/src/command.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: S1-pleasereview

#233 Integrate cargo fmt check in GA
  .github/workflows/build_and_run_test.yml
  Makefile
  node/build.rs
  node/src/chain_spec.rs
  node/src/cli.rs
  node/src/command.rs
  node/src/main.rs
  node/src/rpc.rs
  node/src/service.rs
  primitives/src/lib.rs
  runtime/build.rs
  runtime/src/constants.rs
  runtime/src/impls/mock.rs
  runtime/src/impls/mod.rs
  runtime/src/impls/tests.rs
  runtime/src/lib.rs
  runtime/src/weights/mod.rs
Labels: S1-pleasereview

#235 add local pre-commit hook for `cargo fmt`
  .githooks/README.md
  .githooks/pre-commit
Labels: S1-pleasereview

#240 rework release process
  .github/workflows/build_and_run_test.yml
  .github/workflows/build_docker_with_args.yml
  .github/workflows/build_wasm.yml
  .github/workflows/create_release_draft.yml
  scripts/generate-release-notes.sh
Labels: S1-pleasereview

#241 Integrate cargo clippy check
  .github/workflows/build_and_run_test.yml
  Cargo.lock
  Cargo.toml
  Makefile
  node/Cargo.toml
  node/src/chain_spec.rs
  node/src/cli.rs
  node/src/command.rs
  node/src/rpc.rs
  node/src/service.rs
  runtime/src/impls/mock.rs
  runtime/src/impls/tests.rs
  runtime/src/lib.rs
  runtime/src/weights/mod.rs
Labels: S1-pleasereview

#244 add generate_weights.yml template
  .github/workflows/generate_weights.yml
Labels: S1-pleasereview

#247 fix: membership weight info implementation
  runtime/src/lib.rs
Labels: S1-pleasereview

#248 Small improvements to dependabot config
  .github/dependabot.yml
  .github/workflows/build_and_run_test.yml
Labels: F2-tests/benchmarks/ci, S1-pleasereview

#252 Automate pallet benchmarking
  .github/dependabot.yml
  .github/workflows/generate_weights.yml
  .gitignore
  Makefile
  README.md
  runtime/src/weights/frame_system.rs
  runtime/src/weights/pallet_balances.rs
  runtime/src/weights/pallet_collator_selection.rs
  runtime/src/weights/pallet_collective.rs
  runtime/src/weights/pallet_democracy.rs
  runtime/src/weights/pallet_membership.rs
  runtime/src/weights/pallet_multisig.rs
  runtime/src/weights/pallet_proxy.rs
  runtime/src/weights/pallet_scheduler.rs
  runtime/src/weights/pallet_timestamp.rs
  runtime/src/weights/pallet_treasury.rs
  runtime/src/weights/pallet_utility.rs
  scripts/run-benchmark-pallet-local.sh
  scripts/run-benchmark-pallet-remote.sh
  source/frame_system-weights.rs
  source/local.json
  source/pallet_balances-weights.rs
  source/pallet_utility-weights.rs
Labels: S1-pleasereview
