Repository litentry/litentry-parachain, pull requests merged in 2021-10, with the labels that each got.

#139 Fix benchmark host function error
  Cargo.lock
  Makefile
  node/src/command.rs
  node/src/service.rs
  runtime/Cargo.toml
  source/local.json
Labels: F1-bug, S1-pleasereview

#141 Update dependencies to polkadot-v0.9.11
  Cargo.lock
  docker/generated-dev/dev-2022.json
  docker/generated-dev/docker-compose.yml
  docker/generated-dev/relaychain.Dockerfile
  docker/generated-dev/rococo-local.json
  docker/parachain-launch-config-dev.yml
  node/Cargo.toml
  node/src/chain_spec.rs
  node/src/command.rs
  node/src/main.rs
  node/src/rpc.rs
  node/src/service.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
  ts-tests/package.json
  ts-tests/yarn.lock
Labels: S1-pleasereview

#157 bump generated files to v0.9.11
  docker/generated-staging/docker-compose.yml
  docker/generated-staging/relaychain.Dockerfile
  docker/generated-staging/rococo-local.json
  docker/generated-staging/staging-2022.json
  docker/parachain-launch-config-staging.yml
Labels: S1-pleasereview

#163 add launching pallets from Substrate
  Cargo.lock
  node/src/chain_spec.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: S1-pleasereview

#164 Add help description
  Makefile
Labels: F5-enhancement, S1-pleasereview

#199 Update dependencies to polkadot-v0.9.12
  Cargo.lock
  docker/parachain-launch-config-dev.yml
  node/Cargo.toml
  primitives/Cargo.toml
  runtime/Cargo.toml
  runtime/src/lib.rs
  scripts/launch-local-binary.sh
Labels: S1-pleasereview
