Repository litentry/litentry-parachain, pull requests merged in 2023-08, with the labels that each got.

#1977 Accept wrapped eip191 message when verifying the signature
  tee-worker/app-libs/stf/src/helpers.rs
  tee-worker/app-libs/stf/src/trusted_call.rs
  tee-worker/litentry/core/identity-verification/src/lib.rs
  tee-worker/litentry/core/identity-verification/src/web2/mod.rs
  tee-worker/litentry/core/identity-verification/src/web3/mod.rs
  tee-worker/litentry/primitives/src/lib.rs
  tee-worker/litentry/primitives/src/validation_data.rs
  tee-worker/ts-tests/README.md
  tee-worker/ts-tests/integration-tests/batch.test.ts
  tee-worker/ts-tests/integration-tests/bulk_identity.test.ts
  tee-worker/ts-tests/integration-tests/common/type-definitions.ts
  tee-worker/ts-tests/integration-tests/common/utils/crypto.ts
  tee-worker/ts-tests/integration-tests/common/utils/identity-helper.ts
  tee-worker/ts-tests/integration-tests/examples/direct-invocation/evm-di-examples.ts
  tee-worker/ts-tests/integration-tests/examples/direct-invocation/example.ts
  tee-worker/ts-tests/integration-tests/examples/direct-invocation/substrate-di-examples.ts
  tee-worker/ts-tests/integration-tests/examples/direct-invocation/util.ts
  tee-worker/ts-tests/integration-tests/identity-direct-invocation.test.ts
  tee-worker/ts-tests/integration-tests/identity.test.ts
  tee-worker/ts-tests/integration-tests/vc.test.ts
Labels: C1-noteworthy

#1978 change vc proof signature message
  tee-worker/litentry/core/stf-task/receiver/src/handler/assertion.rs
  tee-worker/ts-tests/integration-tests/common/utils/assertion.ts
Labels: C0-breaking

#1986 Add new achainaable assertions
  primitives/core/src/assertion.rs
  tee-worker/app-libs/stf/src/lib.rs
  tee-worker/litentry/core/assertion-build/src/a10.rs
  tee-worker/litentry/core/assertion-build/src/a11.rs
  tee-worker/litentry/core/assertion-build/src/a2.rs
  tee-worker/litentry/core/assertion-build/src/a4.rs
  tee-worker/litentry/core/assertion-build/src/a7.rs
  tee-worker/litentry/core/assertion-build/src/a8.rs
  tee-worker/litentry/core/assertion-build/src/achainable/amount.rs
  tee-worker/litentry/core/assertion-build/src/achainable/amount_holding.rs
  tee-worker/litentry/core/assertion-build/src/achainable/amount_token.rs
  tee-worker/litentry/core/assertion-build/src/achainable/amounts.rs
  tee-worker/litentry/core/assertion-build/src/achainable/basic.rs
  tee-worker/litentry/core/assertion-build/src/achainable/between_percents.rs
  tee-worker/litentry/core/assertion-build/src/achainable/class_of_year.rs
  tee-worker/litentry/core/assertion-build/src/achainable/date.rs
  tee-worker/litentry/core/assertion-build/src/achainable/date_interval.rs
  tee-worker/litentry/core/assertion-build/src/achainable/date_percent.rs
  tee-worker/litentry/core/assertion-build/src/achainable/mod.rs
  tee-worker/litentry/core/assertion-build/src/achainable/token.rs
  tee-worker/litentry/core/assertion-build/src/lib.rs
  tee-worker/litentry/core/credentials/src/lib.rs
  tee-worker/litentry/core/data-providers/src/achainable.rs
  tee-worker/litentry/core/data-providers/src/lib.rs
  tee-worker/litentry/core/stf-task/receiver/src/handler/assertion.rs
  tee-worker/litentry/primitives/src/lib.rs
Labels: C0-breaking

#2013 Remove polygon and rename BSC in Web3Network
  primitives/core/src/network.rs
  runtime/litentry/src/lib.rs
  runtime/litmus/src/lib.rs
  runtime/rococo/src/lib.rs
  tee-worker/litentry/core/assertion-build/src/lib.rs
  tee-worker/litentry/core/data-providers/src/achainable.rs
  tee-worker/litentry/pallets/identity-management/src/tests.rs
  tee-worker/litentry/primitives/src/identity.rs
  tee-worker/ts-tests/integration-tests/examples/direct-invocation/example.ts
  tee-worker/ts-tests/integration-tests/identity-direct-invocation.test.ts
  tee-worker/ts-tests/parachain-api/build/interfaces/identity/definitions.ts
  tee-worker/ts-tests/parachain-api/build/interfaces/identity/types.ts
  tee-worker/ts-tests/parachain-api/build/interfaces/lookup.ts
  tee-worker/ts-tests/parachain-api/build/interfaces/types-lookup.ts
  tee-worker/ts-tests/parachain-api/build/litentry-parachain-metadata.json
  tee-worker/ts-tests/parachain-api/dist/tsconfig.tsbuildinfo
  tee-worker/ts-tests/parachain-api/prepare-build/interfaces/identity/definitions.ts
  tee-worker/ts-tests/parachain-api/prepare-build/litentry-parachain-metadata.json
Labels: C0-breaking

#2049 add A20 EVM early bird assertion
  primitives/core/src/assertion.rs
  tee-worker/litentry/core/assertion-build/src/a20.rs
  tee-worker/litentry/core/assertion-build/src/lib.rs
  tee-worker/litentry/core/credentials/src/lib.rs
  tee-worker/litentry/core/stf-task/receiver/src/handler/assertion.rs
Labels: D1-feature

#2038 Unify the signature error when verifying web3 identities #2033
  primitives/core/src/error.rs
  tee-worker/app-libs/stf/src/helpers.rs
  tee-worker/ts-tests/parachain-api/build/interfaces/augment-api-tx.ts
  tee-worker/ts-tests/parachain-api/build/interfaces/lookup.ts
  tee-worker/ts-tests/parachain-api/build/interfaces/registry.ts
  tee-worker/ts-tests/parachain-api/build/interfaces/types-lookup.ts
  tee-worker/ts-tests/parachain-api/build/litentry-parachain-metadata.json
  tee-worker/ts-tests/parachain-api/dist/build/interfaces/augment-api-tx.d.ts
  tee-worker/ts-tests/parachain-api/dist/build/interfaces/augment-api-tx.d.ts.map
  tee-worker/ts-tests/parachain-api/dist/build/interfaces/lookup.d.ts
  tee-worker/ts-tests/parachain-api/dist/build/interfaces/lookup.d.ts.map
  tee-worker/ts-tests/parachain-api/dist/build/interfaces/lookup.js
  tee-worker/ts-tests/parachain-api/dist/build/interfaces/registry.d.ts
  tee-worker/ts-tests/parachain-api/dist/build/interfaces/registry.d.ts.map
  tee-worker/ts-tests/parachain-api/dist/build/interfaces/types-lookup.d.ts
  tee-worker/ts-tests/parachain-api/dist/build/interfaces/types-lookup.d.ts.map
  tee-worker/ts-tests/parachain-api/dist/tsconfig.tsbuildinfo
  tee-worker/ts-tests/parachain-api/prepare-build/litentry-parachain-metadata.json
  tee-worker/ts-tests/sidechain-api/dist/tsconfig.tsbuildinfo
Labels: C0-breaking

#2070 make di responses minimalistic
  tee-worker/app-libs/stf/src/trusted_call.rs
  tee-worker/app-libs/stf/src/trusted_call_litentry.rs
  tee-worker/app-libs/stf/src/trusted_call_result.rs
  tee-worker/ts-tests/integration-tests/common/utils/assertion.ts
  tee-worker/ts-tests/parachain-api/build/interfaces/augment-api-tx.ts
  tee-worker/ts-tests/parachain-api/build/interfaces/augment-types.ts
  tee-worker/ts-tests/parachain-api/build/interfaces/identity/definitions.ts
  tee-worker/ts-tests/parachain-api/build/interfaces/identity/types.ts
  tee-worker/ts-tests/parachain-api/build/interfaces/lookup.ts
  tee-worker/ts-tests/parachain-api/build/interfaces/registry.ts
  tee-worker/ts-tests/parachain-api/build/interfaces/types-lookup.ts
  tee-worker/ts-tests/parachain-api/build/litentry-parachain-metadata.json
  tee-worker/ts-tests/parachain-api/dist/build/interfaces/augment-api-tx.d.ts
  tee-worker/ts-tests/parachain-api/dist/build/interfaces/augment-api-tx.d.ts.map
  tee-worker/ts-tests/parachain-api/dist/build/interfaces/augment-types.d.ts
  tee-worker/ts-tests/parachain-api/dist/build/interfaces/augment-types.d.ts.map
  tee-worker/ts-tests/parachain-api/dist/build/interfaces/identity/definitions.d.ts
  tee-worker/ts-tests/parachain-api/dist/build/interfaces/identity/definitions.d.ts.map
  tee-worker/ts-tests/parachain-api/dist/build/interfaces/identity/definitions.js
  tee-worker/ts-tests/parachain-api/dist/build/interfaces/identity/types.d.ts
  tee-worker/ts-tests/parachain-api/dist/build/interfaces/identity/types.d.ts.map
  tee-worker/ts-tests/parachain-api/dist/build/interfaces/lookup.d.ts
  tee-worker/ts-tests/parachain-api/dist/build/interfaces/lookup.d.ts.map
  tee-worker/ts-tests/parachain-api/dist/build/interfaces/lookup.js
  tee-worker/ts-tests/parachain-api/dist/build/interfaces/registry.d.ts
  tee-worker/ts-tests/parachain-api/dist/build/interfaces/registry.d.ts.map
  tee-worker/ts-tests/parachain-api/dist/build/interfaces/types-lookup.d.ts
  tee-worker/ts-tests/parachain-api/dist/build/interfaces/types-lookup.d.ts.map
  tee-worker/ts-tests/parachain-api/dist/src/index.d.ts
  tee-worker/ts-tests/parachain-api/dist/src/index.d.ts.map
  tee-worker/ts-tests/parachain-api/dist/tsconfig.tsbuildinfo
  tee-worker/ts-tests/parachain-api/prepare-build/interfaces/identity/definitions.ts
  tee-worker/ts-tests/parachain-api/prepare-build/litentry-parachain-metadata.json
Labels: C0-breaking

#2059 Update A8 upper bound
  tee-worker/litentry/core/assertion-build/src/a8.rs
  tee-worker/litentry/core/credentials/src/lib.rs
Labels: C0-breaking
