Repository litentry/litentry-parachain, pull requests merged in 2024-01, with the labels that each got.

#2366 Support prettified bitcoin signing message
  primitives/core/src/network.rs
  tee-worker/client-api/parachain-api/prepare-build/interfaces/identity/definitions.ts
  tee-worker/litentry/primitives/src/lib.rs
  tee-worker/ts-tests/integration-tests/common/utils/context.ts
  tee-worker/ts-tests/integration-tests/common/utils/identity-helper.ts
  tee-worker/ts-tests/integration-tests/di_bitcoin_identity.test.ts
Labels: C1-noteworthy

#2373 Replace `T::AccountId` with `Identity` in callback extrinsics
  Cargo.lock
  pallets/identity-management/src/benchmarking.rs
  pallets/identity-management/src/lib.rs
  pallets/identity-management/src/tests.rs
  pallets/vc-management/Cargo.toml
  pallets/vc-management/src/benchmarking.rs
  pallets/vc-management/src/lib.rs
  pallets/vc-management/src/tests.rs
  pallets/vc-management/src/vc_context.rs
  primitives/core/Cargo.toml
  primitives/core/src/identity.rs
  primitives/core/src/lib.rs
  tee-worker/Cargo.lock
  tee-worker/app-libs/stf/src/trusted_call.rs
  tee-worker/app-libs/stf/src/trusted_call_litentry.rs
  tee-worker/core-primitives/utils/src/hex.rs
  tee-worker/enclave-runtime/Cargo.lock
  tee-worker/litentry/core/credentials/src/lib.rs
  tee-worker/litentry/core/vc-issuance/lc-vc-task-receiver/src/lib.rs
  tee-worker/litentry/primitives/src/lib.rs
  tee-worker/ts-tests/integration-tests/common/di-utils.ts
  tee-worker/ts-tests/integration-tests/common/utils/assertion.ts
  tee-worker/ts-tests/integration-tests/common/utils/crypto.ts
  tee-worker/ts-tests/integration-tests/common/utils/identity-helper.ts
  tee-worker/ts-tests/integration-tests/common/utils/storage.ts
  tee-worker/ts-tests/integration-tests/common/utils/vc-helper.ts
  tee-worker/ts-tests/integration-tests/di_bitcoin_identity.test.ts
  tee-worker/ts-tests/integration-tests/di_evm_identity.test.ts
  tee-worker/ts-tests/integration-tests/di_substrate_identity.test.ts
  tee-worker/ts-tests/integration-tests/di_vc.test.ts
  tee-worker/ts-tests/integration-tests/ii_batch.test.ts
  tee-worker/ts-tests/integration-tests/ii_identity.test.ts
  tee-worker/ts-tests/stress/src/litentry-api.ts
  tee-worker/ts-tests/stress/src/steps.ts
  tee-worker/ts-tests/stress/src/user-session.ts
Labels: C0-breaking

#2347 IDGraph should be created in more actions than linking
  tee-worker/app-libs/stf/src/trusted_call.rs
  tee-worker/app-libs/stf/src/trusted_call_litentry.rs
  tee-worker/core/rpc-client/src/mock.rs
  tee-worker/litentry/pallets/identity-management/src/lib.rs
  tee-worker/litentry/pallets/identity-management/src/tests.rs
  tee-worker/ts-tests/integration-tests/di_evm_identity.test.ts
  tee-worker/ts-tests/integration-tests/di_substrate_identity.test.ts
  tee-worker/ts-tests/integration-tests/ii_identity.test.ts
Labels: C1-noteworthy

#2404 Use whole unsigned VC as VC proof signature payload
  pallets/vc-management/src/benchmarking.rs
  pallets/vc-management/src/lib.rs
  pallets/vc-management/src/schema.rs
  pallets/vc-management/src/tests.rs
  pallets/vc-management/src/vc_context.rs
  pallets/vc-management/src/weights.rs
  runtime/litmus/src/weights/pallet_vc_management.rs
  runtime/rococo/src/weights/pallet_vc_management.rs
  tee-worker/app-libs/stf/src/trusted_call.rs
  tee-worker/app-libs/stf/src/trusted_call_result.rs
  tee-worker/client-api/parachain-api/prepare-build/interfaces/vc/definitions.ts
  tee-worker/core-primitives/stf-executor/src/enclave_signer.rs
  tee-worker/core-primitives/stf-executor/src/mocks.rs
  tee-worker/core-primitives/stf-executor/src/traits.rs
  tee-worker/litentry/core/credentials/src/lib.rs
  tee-worker/litentry/core/stf-task/receiver/src/handler/assertion.rs
  tee-worker/litentry/core/vc-issuance/lc-vc-task-receiver/src/lib.rs
  tee-worker/litentry/core/vc-issuance/lc-vc-task-receiver/src/vc_handling.rs
  tee-worker/litentry/core/vc-issuance/lc-vc-task-sender/src/lib.rs
  tee-worker/ts-tests/integration-tests/common/utils/assertion.ts
  tee-worker/ts-tests/integration-tests/common/utils/vc-helper.ts
  tee-worker/ts-tests/integration-tests/ii_vc.test.ts
Labels: C0-breaking

#2420 fix: P-381 VC typo
  tee-worker/litentry/core/credentials/src/nodereal/bnb_domain/bnb_domain_holding_amount.rs
Labels: C0-breaking

#2401 P-54 Binary search for holding time assertion
  primitives/core/src/assertion.rs
  tee-worker/litentry/core/assertion-build/src/holding_time.rs
  tee-worker/litentry/core/assertion-build/src/lib.rs
  tee-worker/litentry/primitives/src/lib.rs
Labels: rust

#2430 Fix assertion identifiers missing the `$` prefix
  tee-worker/litentry/core/credentials/src/achainable/bab_holder.rs
  tee-worker/litentry/core/credentials/src/achainable/lit_holding_amount.rs
Labels: C0-breaking
