Repository litentry/litentry-parachain, pull requests merged in 2024-03, with the labels that each got.

#2539 feat: P-503 added identity Solana, and web3Network Solana
  Cargo.lock
  Cargo.toml
  bitacross-worker/litentry/primitives/src/validation_data.rs
  primitives/core/Cargo.toml
  primitives/core/src/identity.rs
  primitives/core/src/network.rs
  tee-worker/Cargo.lock
  tee-worker/client-api/parachain-api/prepare-build/interfaces/identity/definitions.ts
  tee-worker/enclave-runtime/Cargo.lock
  tee-worker/litentry/core/assertion-build/src/lib.rs
  tee-worker/litentry/core/common/src/lib.rs
  tee-worker/litentry/core/data-providers/src/achainable.rs
  tee-worker/litentry/primitives/src/validation_data.rs
  tee-worker/service/src/prometheus_metrics.rs
Labels: C1-noteworthy

#2533 fix: remove fees for TEE callback extrinsics
  pallets/teebag/src/lib.rs
Labels: D3-chore

#2524 Eliminate warnings in tests mod
  tee-worker/litentry/core/assertion-build-v2/src/nft_holder/mod.rs
  tee-worker/litentry/core/assertion-build-v2/src/platform_user/mod.rs
  tee-worker/litentry/core/assertion-build-v2/src/token_holding_amount/mod.rs
  tee-worker/litentry/core/assertion-build/src/a2.rs
  tee-worker/litentry/core/assertion-build/src/a3.rs
  tee-worker/litentry/core/assertion-build/src/generic_discord_role.rs
  tee-worker/litentry/core/assertion-build/src/holding_time.rs
  tee-worker/litentry/core/assertion-build/src/nodereal/amount_holding/evm_amount_holding.rs
  tee-worker/litentry/core/assertion-build/src/nodereal/nft_holder/weirdo_ghost_gang_holder.rs
  tee-worker/litentry/core/data-providers/src/achainable.rs
  tee-worker/litentry/core/data-providers/src/discord_litentry.rs
  tee-worker/litentry/core/data-providers/src/discord_official.rs
  tee-worker/litentry/core/data-providers/src/karat_dao.rs
  tee-worker/litentry/core/data-providers/src/moralis.rs
  tee-worker/litentry/core/data-providers/src/nodereal_jsonrpc.rs
  tee-worker/litentry/core/data-providers/src/twitter_official.rs
Labels: D5-testing

#2532 P-422 add a batched request vc method
  Makefile
  tee-worker/Cargo.lock
  tee-worker/app-libs/stf/src/trusted_call.rs
  tee-worker/app-libs/stf/src/trusted_call_result.rs
  tee-worker/cli/src/trusted_base_cli/commands/litentry/mod.rs
  tee-worker/cli/src/trusted_base_cli/commands/litentry/request_batch_vc.rs
  tee-worker/cli/src/trusted_base_cli/mod.rs
  tee-worker/cli/src/trusted_operation.rs
  tee-worker/client-api/parachain-api/prepare-build/interfaces/trusted_operations/definitions.ts
  tee-worker/client-api/parachain-api/prepare-build/interfaces/vc/definitions.ts
  tee-worker/core-primitives/top-pool-author/src/author.rs
  tee-worker/core-primitives/top-pool-author/src/mocks.rs
  tee-worker/core-primitives/top-pool-author/src/traits.rs
  tee-worker/core-primitives/top-pool/src/basic_pool.rs
  tee-worker/core-primitives/top-pool/src/listener.rs
  tee-worker/core-primitives/top-pool/src/mocks/rpc_responder_mock.rs
  tee-worker/core-primitives/top-pool/src/mocks/trusted_operation_pool_mock.rs
  tee-worker/core-primitives/top-pool/src/primitives.rs
  tee-worker/core-primitives/top-pool/src/validated_pool.rs
  tee-worker/core-primitives/types/src/lib.rs
  tee-worker/core/direct-rpc-server/src/lib.rs
  tee-worker/core/direct-rpc-server/src/mocks/send_rpc_response_mock.rs
  tee-worker/core/direct-rpc-server/src/rpc_responder.rs
  tee-worker/enclave-runtime/Cargo.lock
  tee-worker/enclave-runtime/src/test/mocks/rpc_responder_mock.rs
  tee-worker/litentry/core/stf-task/receiver/src/lib.rs
  tee-worker/litentry/core/vc-task/receiver/src/lib.rs
  tee-worker/litentry/core/vc-task/sender/src/lib.rs
  tee-worker/sidechain/rpc-handler/Cargo.toml
  tee-worker/sidechain/rpc-handler/src/direct_top_pool_api.rs
  tee-worker/ts-tests/integration-tests/common/di-utils.ts
  tee-worker/ts-tests/integration-tests/common/utils/vc-helper.ts
  tee-worker/ts-tests/integration-tests/dr_vc.test.ts
Labels: C0-breaking

#2583 feat: P-624 added NFP token holding amount VC
  primitives/core/src/web3_token.rs
  tee-worker/cli/src/trusted_base_cli/commands/litentry/request_batch_vc.rs
  tee-worker/cli/src/trusted_base_cli/commands/litentry/request_vc.rs
  tee-worker/client-api/parachain-api/prepare-build/interfaces/vc/definitions.ts
  tee-worker/litentry/core/common/src/web3_token/mod.rs
Labels: C1-noteworthy

#2572 Sol Balance VC with an abort strategy example implementation
  bitacross-worker/docker/docker-compose.yml
  bitacross-worker/docker/multiworker-docker-compose.yml
  local-setup/.env.dev
  primitives/core/src/web3_token.rs
  tee-worker/Cargo.lock
  tee-worker/cli/src/trusted_base_cli/commands/litentry/request_batch_vc.rs
  tee-worker/cli/src/trusted_base_cli/commands/litentry/request_vc.rs
  tee-worker/client-api/parachain-api/prepare-build/interfaces/vc/definitions.ts
  tee-worker/docker/docker-compose.yml
  tee-worker/docker/multiworker-docker-compose.yml
  tee-worker/enclave-runtime/Cargo.lock
  tee-worker/litentry/core/assertion-build-v2/Cargo.toml
  tee-worker/litentry/core/assertion-build-v2/src/token_holding_amount/mod.rs
  tee-worker/litentry/core/assertion-build/src/lib.rs
  tee-worker/litentry/core/common/src/abort_strategy.rs
  tee-worker/litentry/core/common/src/lib.rs
  tee-worker/litentry/core/common/src/web3_token/mod.rs
  tee-worker/litentry/core/data-providers/src/lib.rs
  tee-worker/litentry/core/data-providers/src/moralis.rs
  tee-worker/litentry/core/mock-server/src/lib.rs
  tee-worker/litentry/core/mock-server/src/moralis.rs
  tee-worker/litentry/core/service/src/web3_token/token_balance/mod.rs
  tee-worker/litentry/core/service/src/web3_token/token_balance/sol_balance.rs
Labels: C1-noteworthy

#2604 Add ws support for DI server
  local-setup/launch.py
  tee-worker/Cargo.lock
  tee-worker/cli/lit_ts_integration_test.sh
  tee-worker/cli/src/lib.rs
  tee-worker/core/tls-websocket-server/src/connection.rs
  tee-worker/core/tls-websocket-server/src/lib.rs
  tee-worker/core/tls-websocket-server/src/stream_state.rs
  tee-worker/core/tls-websocket-server/src/test/fixtures/test_server.rs
  tee-worker/core/tls-websocket-server/src/ws_server.rs
  tee-worker/docker/docker-compose.yml
  tee-worker/docker/lit-parentchain-nonce.yml
  tee-worker/docker/lit-test-failed-parentchain-extrinsic.yml
  tee-worker/docker/lit-ts-api-package-build.yml
  tee-worker/docker/multiworker-docker-compose.yml
  tee-worker/enclave-runtime/Cargo.lock
  tee-worker/enclave-runtime/Cargo.toml
  tee-worker/enclave-runtime/src/initialization/mod.rs
  tee-worker/litentry/core/common/src/abort_strategy.rs
  tee-worker/service/src/config.rs
  tee-worker/service/src/sidechain_setup.rs
  tee-worker/ts-tests/integration-tests/.env.local.example
  tee-worker/ts-tests/integration-tests/.env.staging
  tee-worker/ts-tests/worker/resuming_worker.test.ts
Labels: C1-noteworthy

#2609 feat(call verify): support prefixes for user signature
  tee-worker/Cargo.lock
  tee-worker/app-libs/stf/Cargo.toml
  tee-worker/app-libs/stf/src/getter.rs
  tee-worker/app-libs/stf/src/trusted_call.rs
  tee-worker/client-api/parachain-api/prepare-build/interfaces/identity/definitions.ts
  tee-worker/enclave-runtime/Cargo.lock
  tee-worker/litentry/primitives/Cargo.toml
  tee-worker/litentry/primitives/src/lib.rs
  tee-worker/ts-tests/integration-tests/common/utils/identity-helper.ts
  tee-worker/ts-tests/integration-tests/di_bitcoin_identity.test.ts
Labels: C0-breaking
