Repository litentry/litentry-parachain, pull requests merged in 2024-02, with the labels that each got.

#2490 refactor: remove redundant assertion handling code
  tee-worker/litentry/core/stf-task/receiver/src/handler/assertion.rs
  tee-worker/litentry/core/vc-issuance/lc-vc-task-receiver/src/lib.rs
  tee-worker/litentry/core/vc-issuance/lc-vc-task-receiver/src/vc_handling.rs
Labels: D3-chore

#2464 P-261 Refactor Achainable type definitions
  primitives/core/src/assertion.rs
  tee-worker/cli/src/trusted_base_cli/commands/litentry/request_vc.rs
  tee-worker/cli/src/trusted_base_cli/commands/litentry/request_vc_direct.rs
  tee-worker/client-api/parachain-api/prepare-build/interfaces/vc/definitions.ts
  tee-worker/core/direct-rpc-server/src/rpc_watch_extractor.rs
  tee-worker/litentry/core/assertion-build/src/achainable/amount.rs
  tee-worker/litentry/core/data-providers/src/achainable.rs
  tee-worker/ts-tests/integration-tests/common/utils/vc-helper.ts
Labels: C0-breaking

#2495 Use ed25519::Public as vc_pubkey
  bitacross-worker/enclave-runtime/src/attestation.rs
  pallets/teebag/src/lib.rs
  pallets/teebag/src/types.rs
  tee-worker/enclave-runtime/src/attestation.rs
Labels: C1-noteworthy

#2432 Keep the naming of OneBlock consistent
  primitives/core/src/assertion.rs
  tee-worker/cli/src/trusted_base_cli/commands/litentry/request_vc.rs
  tee-worker/cli/src/trusted_base_cli/commands/litentry/request_vc_direct.rs
  tee-worker/client-api/parachain-api/prepare-build/interfaces/vc/definitions.ts
  tee-worker/litentry/core/assertion-build/src/oneblock/course.rs
  tee-worker/litentry/core/assertion-build/src/oneblock/mod.rs
  tee-worker/litentry/core/credentials/src/credential_schema.rs
  tee-worker/litentry/core/stf-task/receiver/src/handler/assertion.rs
  tee-worker/service/src/prometheus_metrics.rs
  tee-worker/ts-tests/integration-tests/common/utils/vc-helper.ts
Labels: C0-breaking
